### ISSUE TITLE
Containerize application with Docker

### ISSUE THREAD

**Issue by nanotaboada** [nanotaboada/ts-node-samples-express-restful#245]
### Description

We need to containerize our TypeScript-based Node.js and Express.js RESTful API for consistency across environments, ease of local development, and eventual deployment. The setup should support mounting a local SQLite database and expose the correct port. This setup should use a multi-stage Dockerfile and Docker Compose with a minimal base file and a development override.

### Suggested Approach

- Add a multi-stage Dockerfile to the root of the repository.
- Use the base image `node:20-alpine` for both build and runtime stages.
- Build the app using TypeScript in the first stage.
- Copy only the necessary artifacts to a minimal second-stage image.
- Create a `nodejs` user and group in the container.
- Add a minimal `docker-compose.yml` file to serve as the base config.
- Add a `docker-compose.override.yml` to configure development-time settings:
  - Set environment variables.
  - Mount source code for live editing (optional).
  - Mount `players-sqlite3.db` to ensure persistence during dev.

### Proposed Solution

`Dockerfile`
```dockerfile
# Stage 1: Build
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Runtime
FROM node:20-alpine
RUN addgroup -S nodejs && adduser -S nodejs -G nodejs
USER nodejs
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./
COPY src/data/players-sqlite3.db ./src/data/players-sqlite3.db
EXPOSE 9000
CMD ["node", "dist/server.js"]
```

`docker-compose.yml`
```yaml
version: '3.8'

services:
  app:
    build: .
```

`docker-compose.override.yml`
```yaml
version: '3.8'

services:
  app:
    container_name: ts-node-samples-express-restful
    environment:
      - NODE_ENV=development
      - PORT=9000
    volumes:
      - .:/app
      - ./src/data/players-sqlite3.db:/app/src/data/players-sqlite3.db
    ports:
      - "9000:9000"
```

### Acceptance Criteria

- The app can be built and run using `docker compose up --build`
- The API is accessible at `http://localhost:9000`.
- The container includes the existing `players-sqlite3.db` file.
The image can be tagged and built using `docker build -t ts-node-samples-express-restful .`.
- The app runs as the non-root `nodejs` user.
- No unnecessary files (e.g. source `.ts`) are included in the runtime image.
