### ISSUE TITLE
Add Docker Compose support with persistent SQLite volume

### ISSUE THREAD

**Issue by nanotaboada** [nanotaboada/ts-node-samples-express-restful#267]
## Description

Currently, the project uses manual Docker build/run commands and stores the SQLite database inside the container filesystem. This violates container immutability and doesn’t persist data between runs.

## Proposed Solution

Introduce Docker Compose to:

- Automate image building and container orchestration
- Mount a Docker-managed volume to persist the SQLite database across container restarts
- Copy a pre-seeded `players-sqlite3.db` from the image to the volume only on first run

## Suggested Implementation

`docker-compose.yml`
```yaml
version: "3.9"

services:
  api:
    image: ts-node-samples-express-restful
    container_name: express-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - sqlite3-data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  sqlite3-data:

```

`Dockerfile`
```yaml
# Copy entrypoint sctipt and pre-seeded database for initialization
COPY --chown=root:root --chmod=755      scripts/entrypoint.sh           /entrypoint.sh
COPY --chown=root:root --chmod=644      src/data/players-sqlite3.db     /app/init/players-sqlite3.db
```

`scripts/entrypoint.sh`
```bash
#!/bin/bash
set -e

DATA_FILE="/app/data/players-sqlite3.db"
SEED_FILE="/app/init/players-sqlite3.db"

echo "🚀 Starting container..."

# Check if the DB already exists in the volume
if [ ! -f "$DATA_FILE" ]; then
    echo "📦 No existing database found in volume."
    echo "🔁 Copying seeded database to writable volume..."
    cp "$SEED_FILE" "$DATA_FILE"
    chown fastapi:fastapi "$DATA_FILE"
    echo "✅ Database initialized at $DATA_FILE"
else
    echo "📂 Existing database found. Skipping seed copy."
fi

echo "✅ Ready!"
echo "📡 Launching app..."

exec "$@"
```

## Acceptance Criteria

- `docker compose up` builds and runs the container with the Express app on port 9000
- SQLite DB is copied to the volume only if not already present
- Data persists after `docker compose down` and is restored on next `up`
- `docker compose down -v` resets the DB, and re-seeds it on next run
- `README.md` is updated with Compose usage instructions
